version: "3.5"
services:
  centos7xdebugphp80:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-8.0
  centos8xdebugphp80:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        image: php-8.0

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
